#!/bin/bash

if [ -z "$SCRIPT_PATH" ]; then
    echo "You must set \$SCRIPT_PATH for this script to work!" >&2
    exit 1;
fi

for SCRIPT in $SCRIPT_PATH/*; do
    SCRIPT_BASENAME=${SCRIPT##*/}
    SCRIPT_SYMLINK="/usr/local/bin/$SCRIPT_BASENAME"

    if [ -L $SCRIPT_SYMLINK ]; then
        # echo "$SCRIPT_BASENAME already exists, removing current symlink..." >&2
        sudo rm $SCRIPT_SYMLINK
    fi

    if ! sudo ln -s $SCRIPT $SCRIPT_SYMLINK &> /dev/null; then
        echo "Failed to link $SCRIPT_BASENAME." >&2
    else
        echo "Successfully linked $SCRIPT_BASENAME at $SCRIPT_SYMLINK."
    fi
done